### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by ranjanan** [ali-ramadhan/Oceananigans.jl#2]
* [Here](https://github.com/ali-ramadhan/OceanLES.jl/blob/master/OceanLES.jl#L6-24) const all the things. 
* For embarrasingly parallel : `pmap` (others = `@parallel`, DistributedArrays, MPIArrays)
* GPU: CuArrays (quick and dirty), GPUArrays (architecture agnostic)

**Comment by ali-ramadhan** [comment]
Thanks for the feedback @ranjanan !
* Instead of using `const` we went with structs.
* CuArrays have worked quite well but still working on writing performant CPU/GPU shared kernels (hoping [GPUifyLoops.jl](https://github.com/vchuravy/GPUifyLoops.jl) will help here).
* Multicore parallelism is a bit lower priority right now but have had some pretty good results with DistributedArrays although I think MPIArrays will be the way forward for us here.
